addSbtPlugin("org.scalameta"      % "sbt-mdoc"                 % "2.3.1")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"           % "1.5.10")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.9.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.1.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.6")
