name: Auto approve Scala Steward

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'scala-steward'
        with:
          github-token: "${{ secrets.SCALA_STEWARD_MERGE_TOKEN }}"
