name: Scala CI

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: "16"
          distribution: "adopt"
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.10.2
      - name: Check sources formatting
        run: sbt scalafmtCheck
      - name: Check sbt and project dir formatting
        run: sbt scalafmtSbtCheck
      - name: Run tests
        run: sbt test
      - name: Build docs
        run: sbt docs/mdoc