name: Scala CI

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Check sources formatting
      run: sbt scalafmtCheck
    - name: Check sbt and project dir formatting
      run: sbt scalafmtSbtCheck
    - name: Run tests
      run: sbt test
    - name: Build docs
      run: sbt docs/mdoc
